-- ====================================================================
-- JASS PRODUCTS SEED SCRIPT
-- Beauty, Skincare & Hair Care Collection
-- ====================================================================

INSERT INTO public.products (
    id, name, slug, category, description, note, price, image, hover_image, gallery, badge, rating, reviews_count, stock, is_featured
) VALUES
  (
    'jp-1',
    'Silky Shine & Anti Dandruff Combo',
    'silky-shine-anti-dandruff-combo',
    'HAIR CARE',
    'Holistic hair care combo formulated with natural botanical extracts to eliminate dandruff while imparting a silky shine.',
    'Scalp and follicle balancing treatment',
    42.00,
    '/newcat-1.png',
    '/newcat-1.png',
    '["/newcat-1.png"]'::jsonb,
    'Best Seller',
    4.9,
    38,
    100,
    true
  ),
  (
    'jp-2',
    'Renew Serum',
    'renew-serum',
    'SKIN RENEWAL',
    'Concentrated botanical renewal serum targeting fine lines, hydration barrier restoration, and cellular turnover.',
    'Fast-absorbing revitalizing facial nectar',
    58.00,
    '/newcat-2.png',
    '/newcat-2.png',
    '["/newcat-2.png"]'::jsonb,
    'Top Rated',
    5.0,
    52,
    75,
    true
  ),
  (
    'jp-3',
    'Pure Essential Oil',
    'pure-essential-oil',
    'AROMATHERAPY',
    '100% pure steam-distilled organic essential oil providing therapeutic calming aromas and rich skin hydration.',
    'Multipurpose aromatherapy essential drops',
    28.00,
    '/newcat-3.png',
    '/newcat-3.png',
    '["/newcat-3.png"]'::jsonb,
    'Organic',
    4.8,
    29,
    80,
    true
  ),
  (
    'jp-4',
    'Balance Toner',
    'balance-toner',
    'TONE & PREP',
    'Gentle balancing toner with witch hazel and rose floral water to refine pores and optimize skin pH levels.',
    'Alcohol-free skin prep infusion',
    34.00,
    'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=600&h=600',
    'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=600&h=600',
    '["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=600&h=600"]'::jsonb,
    'Trending',
    4.7,
    19,
    60,
    true
  ),
  (
    'jp-5',
    'Deep Hydrating Cream Sets',
    'deep-hydrating-cream-sets',
    'FACE NOURISH',
    'Rich ceramide and plant lipid moisture reservoir providing 24-hour hydration lock for tired or dehydrated skin.',
    'Intensive hydration therapy set',
    85.00,
    '/newcat-4.png',
    '/newcat-4.png',
    '["/newcat-4.png"]'::jsonb,
    'Limited Edition',
    4.9,
    44,
    40,
    true
  ),
  (
    'jp-6',
    'Nourishing Body Wash',
    'nourishing-body-wash',
    'BODY CARE',
    'Luxurious non-stripping body wash formulated with plant ceramides and refreshing herbal scents.',
    'Silky botanical body lather',
    32.00,
    '/newcat-1.png',
    '/newcat-1.png',
    '["/newcat-1.png"]'::jsonb,
    NULL,
    4.6,
    22,
    50,
    false
  ),
  (
    'jp-7',
    'Glow Face Mask',
    'glow-face-mask',
    'SKIN RENEWAL',
    'Clarifying antioxidant treatment mask packed with bio-available vitamin C and natural French clay.',
    'Weekly glow and clarify ritual',
    45.00,
    '/newcat-2.png',
    '/newcat-2.png',
    '["/newcat-2.png"]'::jsonb,
    'Popular',
    4.8,
    31,
    35,
    false
  ),
  (
    'jp-8',
    'Calming Sleep Mist',
    'calming-sleep-mist',
    'AROMATHERAPY',
    'Tranquil sleep mist infused with Bulgarian lavender, chamomile, and bergamot essential oils.',
    'Aromatherapeutic nightly pillow mist',
    24.00,
    '/newcat-3.png',
    '/newcat-3.png',
    '["/newcat-3.png"]'::jsonb,
    NULL,
    4.9,
    60,
    90,
    false
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  note = EXCLUDED.note,
  price = EXCLUDED.price,
  image = EXCLUDED.image,
  hover_image = EXCLUDED.hover_image,
  gallery = EXCLUDED.gallery,
  badge = EXCLUDED.badge,
  rating = EXCLUDED.rating,
  reviews_count = EXCLUDED.reviews_count,
  stock = EXCLUDED.stock,
  is_featured = EXCLUDED.is_featured;
